language: python
env:
  - PYTHON=3.5
  - PYTHON=3.6
install:
    # Install conda
    - if [[ "$PYTHON" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a

    # Install deps
    - deps='pip numpy'
    - conda create -q -n pyenv python=$PYTHON $deps
    - source activate pyenv
    - pip install pytest
    - pip install cmake==3.15
    - pip install .

script: pytest --pyargs lapsolver