environment:
  matrix:
    # http://www.appveyor.com/docs/installed-software#python
    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"    

  global:
    CIBW_TEST_REQUIRES: pytest
    CIBW_TEST_COMMAND: "pytest tests"

install:
  - if "%PYTHON_VERSION%" == "3.6" set "BASE_PYTHON_VERSION=36"
  - if "%PYTHON_ARCH%" == "64" set "ARCH_LABEL=-x64"
  - set "CONDA_ROOT=C:\Miniconda%BASE_PYTHON_VERSION%%ARCH_LABEL%"
  - set "PATH=%CONDA_ROOT%;%CONDA_ROOT%\Scripts;%CONDA_ROOT%\Library\bin;%PATH%"
  - conda config --set always_yes yes
  - conda update -q conda
  - conda config --set auto_update_conda no
  #- conda update -q --all
  - conda install -q pip pytest numpy cmake

build:
  - python setup.py bdist_wheel

artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels